### ISSUE TITLE
Meldung über die öffentliche Erreichbarkeit eines Webservers, obwohl dies in diesem Fall nicht iobroker ist

### ISSUE THREAD

**Issue by oweitman** [ioBroker/webserver#6]
Diskussion:
https://forum.iobroker.net/topic/69105/is-reachable-from-internet-without-any-protection/2?_=1697290617689

2023-10-14 13:09:29.625 - error: admin.2 (10377) Error: The URL "http://111.222.333.444:80" is reachable from internet without any protection!

betroffene Stelle im code:
https://github.com/ioBroker/webserver/blob/def4448052333d00321e83eda00ca9ca5f3efc5e/src/lib/securityChecker.ts#L41

Evtl Maßnahme um eine falsch positiv-Meldung auszuschließen:

> Wenn ihr also Ideen habt wie man die false - positive Meldungen reduzieren kann durch Anpassungen an der Logik da man bitte als issue beim Web Adapter anlegen. Danke

auf einer bestimmten url liefert der iobroker ein zertifikat aus oder irgendeine datei, anhand man feststellen kann, das es der iobroker ist.

http(s)://(ip):(port)/proofofiobroker.html
wenn auf dieser url nix kommt, ist es kein iobroker

**Comment by GermanBluefox** [comment]
Interessante Idee
